--中航消费金融数据查询
select t.APPL_SEQ,
       t.APPL_CDE,
       t.APPLY_DT,
       t.INSTU_CDE, --金融机构代码
       t.BCH_CDE, --管理机构
       t.FORM, --业务表单
       t.CUST_ID, --客户号
       t.MSS_IND, --是否接受短信
       t.REJ_IND, --是否曾被拒绝
       t.TYP_GRP, --贷款类型
       t.LOAN_TYP, --贷款品种
       t.GUTR_OPT,
       t.LIC_CITY,
       t.LIMIT_CITY_IND,
       t.AVOID_IND,
       t.LOAN_PROM,
       t.PRO_PUR_AMT,
       t.FST_PCT,
       t.FST_PAY,
       t.VEH_CHASSIS,
       t.PURPOSE,
       t.OTHER_PURPOSE,
       t.APPLY_AMT,
       t.APPRV_AMT,
       t.APPLY_TNR_TYP,
       t.APPLY_TNR,
       t.APPRV_TNR_TYP,
       t.APPRV_TNR
  from lc_appl t;

--贷款申请信息
select t.APPL_SEQ       as 申请流水号,
       t.APPL_CDE       as 申请编号,
       t.INSTU_CDE      as 金融机构代码,
       t.FORM           as 业务表单,
       t.BCH_CDE        as 管理机构,
       t.CUST_ID        as 客户号,
       t.APPLY_DT       as 申请日期,
       --t.ID_TYP         as 证件类型,
       --t.ID_TYP_OTH     as 证件类型其他,
       --t.ID_NO          as 证件号码,
       --t.CUST_NAME      as 客户名称,
       t.MSS_IND        as 是否接受短信,
       t.REJ_IND        as 是否曾被拒绝,
       t.TYP_GRP        as 贷款类型,
       t.LOAN_TYP       as 贷款品种,
       t.TYP_SEQ        as 标识贷款品种顺序号,
       t.TYP_VER        as 贷款品种版本号,
       t.GUTR_OPT       as 抵押选项,
       --t.LIC_CITY       as 上牌城市,
       --t.LIMIT_CITY_IND as 是否限购城市,
       t.AVOID_IND      as 是否免抵押,
       t.LOAN_PROM      as 营销专案,
       t.PRO_PUR_AMT    as 购买总额,
       t.FST_PCT        as 首付比例,
       t.FST_PAY        as 首付金额,
       --t.VEH_CHASSIS    as 发票车架号,
       t.LOAN_CCY       as 币种,
       t.PURPOSE        as 贷款用途,
       t.OTHER_PURPOSE  as 贷款其他用途,
       --t.APPLY_AMT      as 贷款申请金额,
       --t.APPRV_AMT      as 贷款审批金额,
       t.APPLY_TNR_TYP  as 申请期限选项,
       t.APPLY_TNR      as 申请期限,
       t.APPRV_TNR_TYP  as 审批期限选项,
       t.APPRV_TNR      as 审批期限,
       t.LOAN_FREQ      as 还款间隔,
       t.MTH_AMT        as 月还款额,
       t.DUE_DAY_OPT    as 每期还款日,
       t.DUE_DAY        as 还款日,
       t.DSR_RATIO      as 偿债比率,
       t.COLL_RATIO     as 总抵质押率,
       t.WF_APPR_STS    as 审批状态,
       t.IN_STS         as 内部状态,
       t.OUT_STS        as 外部状态,
       t.APP_ORIGIN     as 进单渠道,
       t.DOC_CHANNEL    as 进件通路,
       --t.SCORE          as 信用评分,
       --t.SCORE_GRADE    as 评分级别,
       --t.COMPL_RESULT   as 准入结果,
       t.SIGN_DT        as 签约日期,
       t.CONT_NO        as 合同号,
       --t.CONT_AMT       as 合同金额,
       t.MTD_CDE        as 还款方式,
       t.RATE_TYP       as 利率类型,
       t.MTD_MODE       as 利率模式,
       t.REPC_OPT       as 利率调整方式,
       t.BASIC_INT_RAT  as 基准利率,
       t.PRICE_INT_RAT  as 定价利率,
       t.SUPER_COOPR    as 所属合作机构集团,
       t.COOPR_CDE      as 合作机构代码,
       --t.COOPR_NAME     as 合作机构名称,
       --t.COOPR_ZONE     as 合作机构联系电话区号,
       --t.COOPR_TEL      as 合作机构联系电话,
       --t.COOPR_SUB      as 合作机构联系电话分机,
       --t.SALER_NAME     as 销售员姓名,
       --t.SALER_MOBILE   as 销售员手机,
       t.OPERATOR_CDE   as 客户经理代码,
       --t.OPERATOR_NAME  as 客户经理名称,
       --t.OPERATOR_TEL   as 客户经理联系电话,
       t.LOAN_OPT       as 业务申请类型选项,
       --t.APP_IN_ADVICE  as 录入留言,
       t.CRT_USR        as 创建用户推广人,
       t.CRT_BCH        as 创建用户所在机构,
       t.CRT_BCH_IND    as 创建用户是否为行内用户,
       t.CRT_DT         as 创建日期,
       t.LAST_CHG_DT    as 最后修改时间,
       t.LAST_CHG_USR   as 最后修改用户,
       --t.PROM_NO        as 进件代码,
       t.RATE_RULE      as 定价规则,
       t.cap_cde_sender as 信托计划代码
  from LC_APPL t
 where t.CONT_NO = 'HT201612160800000092111';

select * from lc_appl t where t.CONT_NO is null;

select * from LM_LOAN_CONT t where t.LOAN_CONT_NO = 'HT201612160800000092111001';

select * from LM_LOAN_CONT t where t.LOAN_CONT_NO = 'HT201612160800000092111001';

--贷款合同表
select t.APPL_SEQ        as 申请流水号,
       t.CONT_IND        as 合同生成标志,
       t.CONT_NO         as 合同号,
       t.APPRV_AMT       as 合同金额,
       t.AVAIL_AMT       as 合同可用余额,
       t.DN_AMT          as 累计放款金额,
       t.STR_DT          as 合同起始日期,
       t.END_DT          as 合同结束日期,
       t.LOAN_REPAY_MTHD as 扣款方式,
       t.CHARGEOFF_IND   as 放款方式,
       t.LAST_CHG_USR    as 最后修改人
  from LC_APPL_CONT t
 where t.CONT_NO = 'HT201612160800000092111';

--借据信息表
select t.LOAN_NO              as 借据号,
       t.BANK_CDE             as 银行代码,
       t.BCH_CDE              as 分支机构代码,
       --t.ID_TYPE              as 借款人证件类型,
       --t.ID_NO                as 借款人证件号,
       --t.ISS_CTRY             as 借款人发证国家,
       t.CUST_ID              as 客户编码,
       --t.CUST_NAME            as 借款人姓名,
       t.DEALER_CDE           as 商户经销商代码,
       --t.LOAN_TYP             as 贷款品种代码,
       t.LOAN_CONT_NO         as 贷款合同号,
       --t.LOAN_STS             as 贷款状态,
       --t.TNR                  as 贷款月数,
       t.LAST_DUE_DT          as 最后到期日,
       t.INT_START_DT         as 起息日,
       t.LOAN_DEBT_STS        as 账务状态,
       t.FST_PAYM_DT          as 第一次扣款日,
       t.DUE_DAY              as 还款日,
       t.LOAN_OD_IND          as 拖欠标志,
       t.LOAN_DEVA_IND        as 减值标志,
       t.LOAN_DEVA_DT         as 已减值日期,
       t.LOAN_STP_ACC_IND     as 转表外标志,
       t.LOAN_STP_ACC_DT      as 转表外日期,
       t.LOAN_ACTV_DT         as 放款日期,
       t.LOAN_RATE_MODE       as 利率模式,
       t.RATE_BASE            as 利率计算基础,
       t.LOAN_RATE_TYP        as 利率代码,
       --t.LOAN_INT_RATE        as 贷款执行利率,
       t.LOAN_BASE_RATE       as 借据基准利率,
       t.LOAN_SPRD            as 借据浮动利率,
       t.INT_ADJ_PCT          as 借据利率浮动比例,
       t.LOAN_OD_RATE_TYP     as 罚息利率代码,
       t.LOAN_OD_BASE_RATE    as 罚息基准利率,
       t.LOAN_OD_INT_RATE     as 罚息执行利率,
       --t.LOAN_DIVER_IND       as 贷款挪用标志,
       --t.LOAN_DIVER_INT_RATE  as 贷款挪用利率,
       --t.FIRST_REPC_DT        as 第一次调整日期,
       --t.LAST_GEN_OD_INT_DT   as 上一次结罚息日,
       --t.LAST_INT_ACC_DT      as 上一次计提日,
       --t.LAST_DEVI_INT_ACC_DT as 上一次减值计提日,
       --t.LAST_SETL_DT         as 上一次扣款日,
       --t.CUR_DUE_DT           as 当前归还日期,
       --t.NEXT_DUE_DT          as 下一次还款日,
       --t.NEXT_BILL_DT         as 下一次账单日,
       t.PAYM_FREQ_UNIT       as 还款间隔单位,
       t.PAYM_FREQ_FREQ       as 还款间隔,
       --t.LAST_REPC_DT         as 最近一次调整还款计划日期,
       --t.NEXT_REPC_DT         as 下一次利率调整日期,
       t.LOAN_CCY             as 币种,
       t.ORIG_PRCP            as 发放金额,
       --t.LOAN_OS_PRCP         as 剩余本金,
       t.LOAN_TNR             as 期数,
       --t.LOAN_OS_DAY          as 贷款多余天数,
       t.CHARGE_DT            as 核销日期,
       t.RAT_CHG_EFF_DT       as 利率调整生效日期,
       t.LOAN_GL_ROLE_CDE     as 会计核算规则代码,
       t.BUSS_TYP             as 业务数据来源,
       t.LN_COST_PROD         as 摊余成本积数,
       t.LN_COST_PROD_DT      as 摊余成本积数日期,
       t.LOAN_GRD             as 贷款五级分类代码,
       t.LOAN_PAYM_MTD        as 还款方式,
       t.LOAN_PAYM_TYP        as 还款方式类型,
       t.OD_RATE_ADJ_PCT      as 罚息利率浮动比例,
       t.DIVER_ADJ_PCT        as 挪用利率浮动比例,
       t.INT_BASE             as 利息计算基础,
       --t.CUR_GEN_OD_INT_DT    as 当前结罚息日期,
       --t.LAST_OD_INT_ACC_DT   as 上次计提罚息日期,
       t.LOAN_DEVA_ORD        as 减值顺序,
       t.OLD_LAST_DUE_DT      as 原最后到期日,
       t.PRCS_PAGE_DT_IND     as 处理分页数据标志,
       t.BILL_DAY             as 账单日,
       t.LIS_ID               as 列表编号,
       t.SBSY_IND             as 贴息标志,
       t.ACCT_NO              as 卡号,
       t.LAST_CHG_OD_DT       as 上次转逾期日,
       t.UP_VER               as 更新版本,
       t.NEXT_SYN_RATE_DT     as 下次同步方式表利率日期,
       t.INSTM_IND            as 期供标志,
       t.SBSY_INT_RATE        as 贴息利率,
       t.REM_TERM_PRCP        as 阶段剩余本金,
       t.THD_CNT              as 线程号,
       t.APP_USER_ID          as 申请用户编号,
       t.APP_USER_NAME        as 申请用户名,
       t.APP_USER_ORG_NO      as 申请用户机构号,
       t.RL_INT_RATE          as 真实利率,
       t.cap_cde              as 信托计划代码
  from LM_LOAN t
 where t.LOAN_NO = 'HT201612160800000092111001';

--放款申请
select t.DN_SEQ       as 放款申请流水号,
       t.APPL_SEQ     as 申请流水号,
       t.CONT_NO      as 合同编号,
       t.LOAN_NO      as 借据编号,
       t.DN_AMT       as 放款金额,
       t.DN_STS       as 放款状态,
       t.WF_APPR_STS  as 审批状态,
       --t.RPYM_AC_BANK as 放款账号开户银行,
       --t.RPYM_AC_BCK  as 放款账号开户机构,
       --t.RPYM_AC_NAM  as 放款账号开户名,
       t.RPYM_AC_NO   as 放款账号,
       --t.RPYM_ID_TYP  as 放款账号开户人证件类型,
       --t.RPYM_ID_NO   as 放款账号开户人证件号码,
       --t.DISB_AC_BANK as 还款账号开户银行,
       --t.DISB_AC_BCK  as 还款账号开户机构,
       --t.DISB_AC_NAM  as 还款账号开户名,
       t.DISB_AC_NO   as 还款账号,
       --t.DISB_ID_TYP  as 还款账号开户人证件类型,
       --t.DISB_ID_NO   as 还款账号开户人证件号码,
       t.CRT_DT       as 创建日期,
       t.DN_DT        as 放款日期,
       t.CRT_USR      as 办理人,
       t.GEN_GL_NO    as 授权号,
       t.LAST_CHG_DT  as 最后修改时间,
       t.LAST_CHG_USR as 最新变更用户
  from LPB_APPL_DN t
 where t.CONT_NO = 'HT201612160800000092111';

--还款计划
select t.LOAN_NO             as 借据编码,
       t.PS_PERD_NO          as 期号,
       t.PS_DUE_DT           as 到期日,
       t.PS_BILL_DT          as 账单日,
       t.SBSY_RATE           as 贴息利率,
       t.PS_INSTM_AMT        as 期供金额,
       t.PS_PRCP_AMT         as 本金,
       t.PS_NORM_INT_AMT     as 正常利息,
       t.PS_OD_INT_AMT       as 逾期利息,
       t.PS_COMM_OD_INT      as 复利,
       t.SBSY_INT_AMT        as 贴息金额,
       t.PS_FEE_AMT          as 费用金额,
       t.PROD_PRCP_AMT       as 本金积数,
       t.PROD_INT_AMT        as 利息积数,
       t.PROD_COMM_INT_AMT   as 复利积数,
       t.PROD_FEE_AMT        as 费用积数,
       t.PS_REM_PRCP         as 剩余本金,
       t.PS_INC_TAKEN        as 已计提正常利息,
       t.SETL_PRCP           as 已还本金,
       t.SETL_NORM_INT       as 已还利息,
       t.SETL_OD_INT_AMT     as 已还逾期利息,
       t.SETL_COMM_OD_INT    as 已还复利,
       t.SETL_FEE_AMT        as 已还费用金额,
       t.SETL_OD_INC_TAKEN   as 已还罚息计提金额,
       t.SETL_INC_TAKEN      as 已还利息计提金额,
       --t.PS_INT_RATE         as 贷款执行利率,
       --t.PS_OD_INT_RATE      as 罚息利率,
       t.PS_OD_IND           as 逾期标志,
       t.LAST_SETL_DT        as 最近还款日,
       t.PS_OD_INC_TAKEN     as 已计提逾期利息,
       t.PS_WV_PRCP_AMT      as 减免本金金额,
       t.PS_WV_NM_INT        as 减免正常利息,
       t.PS_WV_OD_INT        as 减免逾期利息,
       t.PS_WV_COMM_INT      as 减免复利,
       t.PRCP_STATE          as 本金状态,
       t.INT_STATE           as 利息状态,
       t.SETL_IND            as 结清标志,
       --t.COMM_OD_GEN_DT      as 上次结罚息日期,
       t.PP_ER_IND           as 当期还款记录是否为主动还款,
       t.PS_GEN_PROD_DT      as 滚积数日期,
       t.PS_CUR_OD_INC_TAKEN as 当期逾期利息计提金额,
       t.GRC_PROD_PRCP       as 宽限期本金积数,
       t.GRC_PROD_INT        as 宽限期利息积数,
       t.GRC_PROD_COMM       as 宽限期复利积数
  from LM_PM_SHD t
 where t.LOAN_NO = 'HT201612160800000092111001';

--实际交易流水
select t.BUSS_TYP           as 处理业务类型,
       t.TX_NO              as 会计分录流水号,
       t.TX_LOG_SEQ         as 交易流水号,
       t.LOAN_NO            as 借据编码,
       t.OLD_DEBT_STS       as 原贷款状态,
       t.NEW_DEBT_STS       as 新贷款状态,
       --t.SETL_MODE          as 还款模式,
       --t.SETL_TYP           as 还款类型,
       t.SETL_RECV_AMT      as 收到金额,
       t.SETL_VAL_DT        as 生效日期,
       t.SETL_REVSE_IND     as 冲正标志,
       t.SETL_CREATE_DT     as 创建日期,
       t.SETL_CREATE_USR    as 创建用户,
       t.SETL_OD_PRCP_AMT   as 归还欠本金额,
       t.SETL_INT_AMT       as 归还正常利息金额,
       t.SETL_OD_INT_AMT    as 归还罚息金额,
       t.SETL_OD_COMM_INT   as 归还复利金额,
       t.SETL_FEE_AMT       as 归还费用金额,
       t.SETL_REM_PRCP_PAYM as 提前还本金额,
       t.SETL_REVSE_RMK     as 冲正备注,
       t.SETL_REVSE_TX_NO   as 冲正交易号,
       t.SETL_REVSE_DT      as 冲正日期,
       t.SETL_REVSE_USR     as 冲正用户,
       t.SETL_FPAID_INT_OPT as 利息计算到,
       t.SETL_ACC_INT       as 应计利息,
       t.SETL_COMP_IND      as 代偿标志,
       t.SETL_PRCP_IND      as 是否允许只还本金,
       t.GEN_GL_IND         as 生成会计分录标志,
       t.PAYM_PERD_CNT      as 还款后期数,
       t.APD_PROD_IND       as 补记罚息标志,
       t.PP_RAT_BASE        as 提前还款利息选项,
       t.FIRST_PAY_DT       as 提前还款后的首次还款日,
       t.TRUE_RECV_AMT      as 在清偿模式下的实际还款金额,
       t.INPUT_PROOF        as 凭证号,
       t.INPUT_PROOF_TYPE   as 凭证类型,
       t.LAST_PAY_DT        as 最后还款日期,
       t.NEW_INSTM_AMT      as 新期供金额,
       t.PP_PAY_INT_AMT     as 提前划款附加利息,
       --t.LOAN_INT_RATE      as 贷款执行利率,
       t.CLEAR_OWE_IND      as 是否清偿还款,
       t.PRCP_GL_CDE        as 本金科目,
       t.DP_TYP             as 置换
  from LM_SETLMT_LOG t
 where t.LOAN_NO = 'HT201612160800000092111001';

select t.GUTR_OPT,t.* from lc_appl t where t.APPL_SEQ in( '3000463','2527307');

--抵押房屋
select * from LC_APPL_HOUSE t where t.APPL_SEQ = '3000463';

--抵押商品
select * from LC_APPL_GOODS t where t.APPL_SEQ = '2527307';

select * from LC_APPL_GURT t where t.APPL_SEQ in ( '3000463','2527307');
