create or replace view v_dim_pe_divide_scheme as
select "L_SCHEME_ID","L_PROJ_ID","C_SCHEME_TYPE","C_SCHEME_TYPE_N","L_DIVIDE_ID","C_DIVIDE_WAY","C_DIVIDE_WAY_N","C_OBJECT_TYPE","C_OBJECT_TYPE_N","L_OBJECT_ID","C_OBJECT_NAME","F_DIVIDE_RATE","L_EFFECTIVE_DATE","L_EXPIRATION_DATE","L_EFFECTIVE_MONTH","L_EXPIRATION_MONTH","L_EFFECTIVE_FLAG","L_DATA_DATE" from dim_pe_divide_scheme;
