--项目要素
select t.c_proj_code      as 项目编码,
       t.c_proj_name      as 项目名称,
       t.c_name_full      as 项目全称,
       t.d_setup          as 成立日期,
       t.d_preexp         as 预计到期日期,
       t.d_expiry         as 终止日期,
       t.c_proj_phase     as 项目阶段,
       t.c_proj_phase_n   as 项目阶段,
       t.c_proj_status    as 项目状态,
       t.c_proj_status_n  as 项目状态,
       t.c_dept_code      as 部门编码,
       s.c_dept_name      as 部门名称,
       t.c_tstmgr_code    as 信托经理编码,
       r.c_emp_name       as 信托经理名称,
       t.l_netvalue_flag  as 是否净值型,
       t.c_special_type   as 特殊类型,
       t.c_special_type_n as 特殊类型,
       t.c_busi_scope     as 业务范围,
       t.c_busi_scope_n   as 业务范围,
       t.c_proj_type      as 项目类别,
       t.c_proj_type_n    as 项目类别,
       t.c_manage_type    as 管理方式,
       t.c_manage_type_n  as 管理方式,
       t.c_func_type      as 功能分类,
       t.c_func_type_n    as 功能分类,
       t.c_trust_type     as 信托类型,
       t.c_trust_type_n   as 信托类型,
       t.c_fduse_way      as 资金运用方式,
       t.c_fduse_way_n    as 资金运用方式,
       t.c_invest_indus   as 投向行业,
       t.c_invest_indus_n as 投向行业,
       t.c_invest_dir     as 投向方向,
       t.c_invest_dir_n   as 投向方向,
       t.c_coop_type      as 合作类型,
       t.c_coop_type_n    as 合作类型
  from tde_project t, tde_department s, tde_employee r
 where t.c_dept_code = s.c_dept_id
   and t.c_tstmgr_code = r.c_emp_code
 order by t.d_setup;
