--查询表空间使用率
SELECT TOTAL.TABLESPACE_NAME,
       ROUND(TOTAL.MB, 2) AS TOTAL_MB,
       ROUND(TOTAL.MB - FREE.MB, 2) AS USED_MB,
       ROUND((1 - FREE.MB / TOTAL.MB) * 100, 2) || '%' AS USED_PCT
  FROM (SELECT TABLESPACE_NAME, SUM(BYTES) / 1024 / 1024 AS MB
          FROM DBA_FREE_SPACE
         GROUP BY TABLESPACE_NAME) FREE,
       (SELECT TABLESPACE_NAME, SUM(BYTES) / 1024 / 1024 AS MB
          FROM DBA_DATA_FILES
         GROUP BY TABLESPACE_NAME) TOTAL
 WHERE FREE.TABLESPACE_NAME = TOTAL.TABLESPACE_NAME;